# Generated by Django 2.2.9 on 2020-04-11 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.ImageField(blank=True, upload_to='upload')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('tag', models.BooleanField(default=False)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod', to='users.ProductCategory')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('middle_name', models.CharField(default='', max_length=255)),
                ('dob', models.DateField(default='2000-01-01', verbose_name='dob')),
                ('gender', models.CharField(choices=[('***', 'M/F'), ('M', 'Male'), ('F', 'Female')], default='', max_length=10)),
                ('phone_no', models.CharField(default=0, max_length=13)),
                ('home_address', models.CharField(default='', max_length=255)),
                ('location', models.CharField(choices=[('Parish', '***select***'), ('Kingston', 'Kingston'), ('St. Andrew', 'St. Andrew'), ('Portland', 'Portland'), ('St. Thomas', 'St. Thomas'), ('St. Catherine', 'St. Catherine'), ('St. Mary', 'St. Mary'), ('St. Ann', 'St. Ann'), ('Manchester', 'Manchester'), ('Clarendon', 'Clarendon'), ('Hanover', 'Hanover'), ('Westmoreland', 'Westmoreland'), ('St. James', 'St. James'), ('Trelawny', 'Trelawny'), ('St. Elizabeth', 'St. Elizabeth')], default='', max_length=50)),
                ('employee_number', models.IntegerField(default=0)),
                ('regulation_number', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('trn', models.CharField(default=0, max_length=11)),
                ('employer', models.CharField(default='', max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
