# Generated by Django 2.2.9 on 2020-04-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsubcategory',
            old_name='tag',
            new_name='is_interested',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
