# Generated by Django 2.2.9 on 2020-04-13 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200413_0147'),
        ('users', '0003_auto_20200412_2309'),
    ]

    operations = [
    ]
