# Generated by Django 2.2.9 on 2020-04-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200416_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='regulation_number',
            field=models.IntegerField(default=0),
        ),
    ]
