# Generated by Django 2.2.9 on 2020-04-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200416_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategory',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
