# Generated by Django 2.2.9 on 2020-04-29 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_confirmemailnew'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmemailnew',
            old_name='email',
            new_name='user',
        ),
    ]
