# Generated by Django 2.2.9 on 2020-04-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200429_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmemailnew',
            name='code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='confirmemailnew',
            name='user',
            field=models.EmailField(max_length=255, verbose_name='email address'),
        ),
    ]
