# Generated by Django 2.2.9 on 2020-04-29 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200429_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmEmail',
        ),
    ]
