# Generated by Django 2.2.9 on 2020-04-30 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_delete_confirmemail'),
        ('users', '0004_merge_20200413_0244'),
    ]

    operations = [
    ]
