# Generated by Django 2.2.9 on 2020-04-13 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
